#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
CGO_ENABLED=0 go build \
    -trimpath \
    -buildvcs=false \
    -tags "netgo osusergo" \
    -ldflags "-buildid= -s -w -X main.GITCOMMIT=$VERSION" \
    -o bin/host-provisioner
