#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running tests

CGO_ENABLED=1 go test -race -cover -tags=test ./...
CGO_ENABLED=1 go test -race -timeout 30s ./vendor/golang.org/x/crypto/ssh -run TestPastureStack
